// ==============================================================================
// PROMPTIFY REAL-WORLD AGRIBANK LAB CURRICULUM DATA
// Re-exported from curriculumSeed generated by: npm run curriculum:seed
// ==============================================================================

import { LabStep } from '../types';
import { SEED_LABS_DATA } from './curriculumSeed';

export const LABS_DATA: LabStep[] = SEED_LABS_DATA;

/**
 * Helper tìm kiếm bài Lab theo UUID chuẩn database hoặc alias ngắn ('lab-1'..'lab-8')
 */
export function findLabByIdOrAlias(idOrAlias: string): LabStep | undefined {
  if (!idOrAlias) return undefined;
  
  // 1. Khớp chính xác ID UUID
  const directMatch = LABS_DATA.find((l) => l.id === idOrAlias);
  if (directMatch) return directMatch;
  
  // 2. Khớp theo alias dạng 'lab-1', 'lab-2',...
  const aliasMatch = idOrAlias.match(/^lab-(\d+)$/i);
  if (aliasMatch) {
    const order = Number(aliasMatch[1]);
    return LABS_DATA.find((l) => l.order === order);
  }
  
  // 3. Khớp theo lessonKey ('LAB-01-PII-SCRUBBING',...)
  return LABS_DATA.find((l) => l.conceptTag.toLowerCase() === idOrAlias.toLowerCase());
}
